### ISSUE TITLE
considered a name change?

### ISSUE THREAD

**Issue by bobafetthotmail** [disks86/VK9#1]
something with Vulkan in the name, like say ShaeferVulkan instead.

Also, you're in the news here http://www.phoronix.com/scan.php?page=news_item&px=SchaeferGL-D3D9-Over-Vulkan

**Comment by disks86** [comment]
Thank you for the suggestion. It didn't originally use Vulkan which is why it wasn't in the name. I'll likely take suggestions from the community for alternative names.

**Comment by AsuMagic** [comment]
Just switching SchaeferGL to SchaeferVK would make the name minimally meaningful.
VK Nine could work a similar fashion as Gallium Nine, but I'm not sure if it would be really fit well.

**Comment by PeyTy** [comment]
+1 for SchaeferVK, you can just set this name right now, Github will keep old links and redirect. Git will chacnhe origin to SchaeferVK on next `git pull` automatically.

**Comment by disks86** [comment]
Any other suggestions?

**Comment by ape123** [comment]
DirectVK? DirectVulkan?

**Comment by disks86** [comment]
hmm, maybe. Anyone have a clever play on words I can use?

**Comment by DistantThunder** [comment]
I might be better to keep it simple and explicit, thus picking amongst the current propositions. I'm in favour of something like "NineVK" unless you plan on adding DX11 compatibility at some point in the future.

**Comment by Two-Tone** [comment]
IMO, VK9/VKNine rolls off the tongue better than NineVK.

**Comment by disks86** [comment]
VK9 sounds reasonable. Any objections?

**Comment by DistantThunder** [comment]
Sounds good from here.

Le 23 août 2016 12:57 AM, "Christopher Schaefer" <notifications@github.com>
a écrit :

VK9 sounds reasonable. Any objections?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/disks86/SchaeferGL/issues/1#issuecomment-241576442>,
or mute
the thread

**Comment by disks86** [comment]
The name has been updated.
