### ISSUE TITLE
Environment variable for Vulkan SDK and Boost

### ISSUE THREAD

**Issue by CookiePLMonster** [disks86/VK9#14]
Maybe instead of hardcoding paths in the project settings, $(VULKAN_SDK) and $(BOOST_ROOT) should be used? That'd make the source portable, leaving out only glm - which probably can be checked in the repository.

**Comment by disks86** [comment]
BOOST_ROOT doesn't appear to exist on my machine. I like the idea of this though apart from included GLM in the repository. Any other suggestions for handling GLM?

**Comment by CookiePLMonster** [comment]
BOOST_ROOT indeed isn't being automatically added by the build process but it's somewhat a common convention when one uses Boost. Maybe just ask the user to ensure those environment variables (maybe also ask for GLM_ROOT - I haven't found any docs about glm's preferred env vars) before they can build it?

**Comment by disks86** [comment]
I switched the include and lib paths for Vulkan to the environment variable. For boost I feel like we need some time of fallback if it's not defined same with glm. Maybe a pre-build script.

**Comment by CookiePLMonster** [comment]
Could do - easiest to check if those paths exist and abort the build if they don't, asking the user to add them. 

Oh and, you also have DXSDK_DIR for DirectX sdk!

**Comment by disks86** [comment]
Added DirectX environment variable.

**Comment by disks86** [comment]
Quick update on this I replaced GLM with another library for math.

**Comment by disks86** [comment]
Closing this because remaining libraries don't have default environment variables and there is a separate effort to implement a build system.
