### ISSUE TITLE
How can I use the DLL with wine?

### ISSUE THREAD

**Issue by gcavalcante8808** [disks86/VK9#20]
Hello Folks,

How may I use the dll with wine?

I tried to copy it into the system32 folder of wine prefix and then changed the d3d9.dll into the native mode.

When I try to run BlackOps, the following log is generated:

[]: C9::GetAdapterMonitor is not implemented!
[]: C9::CheckDeviceFormat is not implemented!22 1094800211
[]: C9::CheckDepthStencilMatch is not implemented!
[]: C9::CheckDeviceFormat is not implemented!22 75
[]: C9::CheckDeviceFormat is not implemented!22 83
[]: C9::CheckDepthStencilMatch is not implemented!
[]: C9::CheckDeviceMultiSampleType is not implemented!
[]: C9::GetAdapterMonitor is not implemented!
[]: ShaderConverter::Convert OP code 65534
[]: ShaderConverter::Convert OP code 21571
[]: ShaderConverter::Convert OP code 28
[]: ShaderConverter::Convert OP code 127
[]: ShaderConverter::Convert OP code 768
[]: ShaderConverter::Convert OP code 2
[]: ShaderConverter::Convert OP code 28
[]: ShaderConverter::Convert OP code 258
[]: ShaderConverter::Convert OP code 120
[]: ShaderConverter::Convert OP code 68
[]: ShaderConverter::Convert OP code 2
[]: ShaderConverter::Convert OP code 4
[]: ShaderConverter::Convert OP code 92
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 108
[]: ShaderConverter::Convert OP code 2
[]: ShaderConverter::Convert OP code 4
[]: ShaderConverter::Convert OP code 92
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 26998
[]: ShaderConverter::Convert OP code 29264
[]: ShaderConverter::Convert OP code 25445
[]: ShaderConverter::Convert OP code 28271
[]: ShaderConverter::Convert OP code 29300
[]: ShaderConverter::Convert OP code 43776
[]: ShaderConverter::Convert OP code 3
[]: ShaderConverter::Convert OP code 4
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 28535
[]: ShaderConverter::Convert OP code 19812
[]: ShaderConverter::Convert OP code 26994
[]: ShaderConverter::Convert OP code 29558
[]: ShaderConverter::Convert OP code 12383
[]: ShaderConverter::Convert OP code 25449
[]: ShaderConverter::Convert OP code 28531
[]: ShaderConverter::Convert OP code 10272
[]: ShaderConverter::Convert OP code 17440
[]: ShaderConverter::Convert OP code 14680
[]: ShaderConverter::Convert OP code 24936
[]: ShaderConverter::Convert OP code 8306
[]: ShaderConverter::Convert OP code 28781
[]: ShaderConverter::Convert OP code 29285
[]: ShaderConverter::Convert OP code 12590
[]: ShaderConverter::Convert OP code 14135
[]: ShaderConverter::Convert OP code 12336
[]: ShaderConverter::Convert OP code 43776
[]: ShaderConverter::Convert OP code 81
[]: ShaderConverter::Convert OP code 8
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 31
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 31
[]: ShaderConverter::Convert OP code 10
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 31
[]: ShaderConverter::Convert OP code 5
[]: ShaderConverter::Convert OP code 2
[]: ShaderConverter::Convert OP code 31
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 31
[]: ShaderConverter::Convert OP code 10
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 31
[]: ShaderConverter::Convert OP code 5
[]: ShaderConverter::Convert OP code 2
[]: ShaderConverter::Convert OP code 4
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 8
[]: ShaderConverter::Convert OP code 8
[]: ShaderConverter::Convert OP code 9
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 4
[]: ShaderConverter::Convert OP code 9
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 5
[]: ShaderConverter::Convert OP code 9
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 6
[]: ShaderConverter::Convert OP code 9
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 7
[]: ShaderConverter::Convert OP code 9
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 9
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 9
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 2
[]: ShaderConverter::Convert OP code 9
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 3
[]: ShaderConverter::Convert OP code 5
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 2
[]: ShaderConverter::Convert OP code 2
[]: ShaderConverter::Convert OP code 65534
[]: ShaderConverter::Convert OP code 21571
[]: ShaderConverter::Convert OP code 28
[]: ShaderConverter::Convert OP code 87
[]: ShaderConverter::Convert OP code 768
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 28
[]: ShaderConverter::Convert OP code 258
[]: ShaderConverter::Convert OP code 80
[]: ShaderConverter::Convert OP code 48
[]: ShaderConverter::Convert OP code 3
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 64
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 28515
[]: ShaderConverter::Convert OP code 19826
[]: ShaderConverter::Convert OP code 24915
[]: ShaderConverter::Convert OP code 25964
[]: ShaderConverter::Convert OP code 4
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 29552
[]: ShaderConverter::Convert OP code 12383
[]: ShaderConverter::Convert OP code 25449
[]: ShaderConverter::Convert OP code 28531
[]: ShaderConverter::Convert OP code 10272
[]: ShaderConverter::Convert OP code 17440
[]: ShaderConverter::Convert OP code 14680
[]: ShaderConverter::Convert OP code 24936
[]: ShaderConverter::Convert OP code 8306
[]: ShaderConverter::Convert OP code 28781
[]: ShaderConverter::Convert OP code 29285
[]: ShaderConverter::Convert OP code 12590
[]: ShaderConverter::Convert OP code 14135
[]: ShaderConverter::Convert OP code 12336
[]: ShaderConverter::Convert OP code 43776
[]: ShaderConverter::Convert OP code 31
[]: ShaderConverter::Convert OP code 10
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 31
[]: ShaderConverter::Convert OP code 5
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 31
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 2048
[]: ShaderConverter::Convert OP code 66
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 1
[]: ShaderConverter::Convert OP code 2048
[]: ShaderConverter::Convert OP code 5
[]: ShaderConverter::Convert OP code 2048
[]: ShaderConverter::Convert OP code 0
[]: ShaderConverter::Convert OP code 0
[]: CTexture9::CTexture9 vkCreateImage failed with return code of -1000011001

Is there any other configuration that must be done before using vk9?

**Comment by Eignar17** [comment]
your problem is VK9 project not full missing code new implementations to run a game

**Comment by disks86** [comment]
Shader support is still in progress all of those op code messages are related to shaders.
