### ISSUE TITLE
What version of boost library is used in this project?

### ISSUE THREAD

**Issue by xlpiao** [disks86/VK9#21]
@disks86 
Could you tell me what version of boost library is used in this project? Where did you download it? I cannot build the project without correct version of boost library.

**Comment by disks86** [comment]
It's boost 1.63.0 It's been a while since I downloaded it but I think it was here.

https://sourceforge.net/projects/boost/files/boost-binaries/1.63.0/

**Comment by xlpiao** [comment]
@disks86 
Hi, the boost library is successfully installed.

However, there needs Eigan library and spirv.hpp.

I think, you should provide detail guideline about building this project. There's no such documentation.

**Comment by xlpiao** [comment]
What I did is, installing following library, but I still cannot build it successfully.
(1) VulkanSDK 1.0.46.
(2) boost library
(3) Eigan library
```

```
Could you please add more detail guideline to build this project?

**Comment by disks86** [comment]
It seems like it's missing all of the vulkan symbols. What version of Visual Studio are you running?
