### ISSUE TITLE
Missing D3DPERF_SetOptions

### ISSUE THREAD

**Issue by uq1** [disks86/VK9#25]
I saw this project and got very interested. Unfortunately I have had no luck getting it to work with anything. Everything that I have tried to use it with has complained about the missing entry point D3DPERF_SetOptions and immediately closes.

**Comment by disks86** [comment]
I took a look and it's because I was only defining the Direct3DCreate9 & Direct3DCreate9Ex entry points. I added stubs for the D3DPERF ones however I'm in the middle of a big refactor right now so I can't test this until that is finished. I'll leave this open until I'm able to test the change.

**Comment by disks86** [comment]
The refactor is finished, however I'm still fixing regressions.

**Comment by uq1** [comment]
Awesome. I look forward to trying it again.

**Comment by rakhenmanoa** [comment]
Hi, do you think that vk9 will work on intel anv driver since dxvk doesn't ?

**Comment by Yardanico** [comment]
@rakhenmanoa maybe it will make more sense to make an issue in dxvk repo? And dxvk aims for dx11, not for dx9

**Comment by rakhenmanoa** [comment]
@Yardanico Intel gpus are not officially supported due to some missing features with the anv vulkan driver. I just want to know if vk9 need these missing features also.

**Comment by Yardanico** [comment]
@rakhenmanoa VK9 is for now at (AFAIK) much earlier stage of development

**Comment by rakhenmanoa** [comment]
@Yardanico but will it work on intel gpus ? That is the question.

**Comment by Yardanico** [comment]
@rakhenmanoa as I said, it's probably unknown for now. You'd better ask Intel devs to add missing functionality

**Comment by rakhenmanoa** [comment]
@Yardanico Yes, Maybe they will add the missing functionalities in the future. It's just that even at it first stage the developper of dxvk said that intel gpus are not supported since the missing features are the most important ones needed to implement dx11 on vulkan. That's why i wanted to know for vk9.  But maybe as you said we need to wait a little more to find out.

**Comment by disks86** [comment]
I have only tested on AMD and Nvidia. I have not tested VK9 with intel graphics drivers. This is better suited for the community discord but I'm curious what your use case for Intel integrated graphics with VK9 would be.

**Comment by disks86** [comment]
@uq1 The latest release contains the entry points. Can you confirm that this is resolved for you?

**Comment by disks86** [comment]
Closing issue because it appears to be resolved and has been inactive for over a month.
