### ISSUE TITLE
Making it easier to compile for Wine?

### ISSUE THREAD

**Issue by Valmar33** [disks86/VK9#27]
Is there a way to make VK9 easier to build for those of us who only use Linux and Wine without any Windows?

**Comment by disks86** [comment]
Not easily pretty much anything else would be a huge time sink. I release binaries when I hit milestones though so people don't necessarily need to build from source to try it out. I also do early builds for patreons.

**Comment by disks86** [comment]
This is resolved now that mmmaisel's pull request has been merged.
