### ISSUE TITLE
No installation guide!

### ISSUE THREAD

**Issue by gnanini** [disks86/VK9#28]
Please leave some kind of installation guide as dxvk does in your Readme.md!

I'm using the gallium nine patch and a want to test this out!

**Comment by disks86** [comment]
I haven't run this in Wine yet but I'll be sure to create some documentation when I test it like that.

**Comment by mmmaisel** [comment]
I added build instructions for Linux with meson to my experimental [meson branch](https://github.com/mmmaisel/VK9).

**Comment by disks86** [comment]
This is resolved now that mmmaisel's pull request has been merged.
