### ISSUE TITLE
VK9 does not compile in 64bit mode.

### ISSUE THREAD

**Issue by mmmaisel** [disks86/VK9#31]
Compiling VK9 in 64bit mode fails with various errors.
The following errors occur with Visual Studio 2017 and GCC 7.3.

Utilities.h:1099 bit_cast fails between DWORD, float and void* because sizeof(void*) now 8 instead of 4.
GCC:  Static assertion fails in Utilities.h:1099
MSVC: Warnings about possible data loss, static_assert seems to be ignored
Possible solution: Use fixed 32bit type instead of void* for WorkItem->ArgumentN and other occurances.

ShaderConverter.cpp:406 and similar lines
GCC:  Mismatched type error between size_type and int
MSVC: template paramter _Ty is ambiguous
Solution: replace "1U" with "(size_t)1"

ShaderConverter.cpp:67 and similar lines
GCC and MSVC: error: ambiguous overload for ‘operator!=’ (operand types are ‘vk::ShaderModule’ and ‘std::nullptr_t’)
Solution: Change "nullptr" to vk object, e.g. "vk::ShaderModule(nullptr)"

Assignment or comparison with VK_NULL_HANDLE: e.g. Perf_StateManager.h:1288
GCC: Conversion from "int" to vk object is ambiguous
MSVC: Operator = is ambiguous
Solution: Change "VK_NULL_HANDLE" to "nullptr"

See my [64bit](https://github.com/mmmaisel/VK9/tree/64bit) branch for some untested fixes.

**Comment by disks86** [comment]
Thank you for pointing this out. I haven't tried to build 64bit yet.

**Comment by disks86** [comment]
I implemented a few if these. The static assert on GCC seems like GCC being picky though as MSVC just treats it as a warning. I don't use GCC for this project but you might be able to work around that with a compiler flag.

**Comment by mmmaisel** [comment]
According to the C++ standard, static_assert should generate a compiler error so it is not possible to ignore this with a compiler flag. If the code works fine even if the assertion is failed, the static_assert should be changed to a "static_warning" (see [here](https://stackoverflow.com/questions/8936063/does-there-exist-a-static-warning)) or simply removed for best portability.

**Comment by disks86** [comment]
I get that but aren't we talking about a compiler generated static_assert?
