### ISSUE TITLE
Any fresh builds?

### ISSUE THREAD

**Issue by Monsterovich** [disks86/VK9#35]
The latest build is over 1 month old.

**Comment by disks86** [comment]
I plan to put out another build when I reach the next milestone. I'm targeting this month for the next milestone but I've been working more hours at my day job so it might be a little tight.

**Comment by Kerrung** [comment]
> I plan to put out another build when I reach the next milestone. I'm targeting this month for the next milestone but I've been working more hours at my day job so it might be a little tight.

@disks86 
It would be desirable in a new release that there would be a 64bit version too.

**Comment by Kerrung** [comment]
>I'll see what I can do.

@disks86, Thank you!

**Comment by disks86** [comment]
I just posted a new release with builds. There is a 32bit and 64bit build. [](https://github.com/disks86/VK9/releases/tag/0.26.0)
