### ISSUE TITLE
Question about github releases: Are they i386 or amd64?

### ISSUE THREAD

**Issue by Zeioth** [disks86/VK9#36]
It would be really, really usefull to have releases for both 32 and 64 bits in the same zip, like [DXVK does](https://github.com/doitsujin/dxvk/releases).

**Comment by disks86** [comment]
The current builds are all 32bit. A few patches were submitted recently to allow vk9 to build on 32bit but I don't have that setup in Visual Studio yet. Out of curiosity what 64bit applications/games are trying to use?

**Comment by Kerrung** [comment]
> Out of curiosity what 64bit applications/games are trying to use?

StarCraft 2, for example.

**Comment by Kerrung** [comment]
@disks86 
> Out of curiosity what 64bit applications/games are trying to use?

StarCraft 2, for example.

**Comment by PadreAdamo** [comment]
Guild Wars 2 is also a popular 64.bit to run through Wine on linux

**Comment by Zeioth** [comment]
I was thinking on Guild Wars too.

Another experiment i wanted to do is to use vk9 with cemu. If vk9 has it own shader cache, it would be a workaround to the current [shader cache limitation](https://devtalk.nvidia.com/default/topic/1032059/opengl-shader-disk-cache-max-size-garbage-collection-/?offset=12#5257882) of nvidia cards.

**Comment by Kerrung** [comment]
@Zeioth, DXVK developer removed the built-in DXVK shader cache. Drivers of all vendors already have their own shader cache implementation.
For Mesa drivers: ~/.cache/mesa
For Nvidia blob: ~/.NV

**Comment by Zeioth** [comment]
Well I guess Nvidia will fix it... Eventually.

**Comment by Kerrung** [comment]
@Zeioth, there's nothing to fix, because, as I just said the shader cache is already implemented in the drivers themselves, that's why he removed the built-in DXVK shader cache.

**Comment by Zeioth** [comment]
Read my previous message and you'll see I'm speaking about the [current limitation](https://devtalk.nvidia.com/default/topic/1032059/opengl-shader-disk-cache-max-size-garbage-collection-/?offset=12#5257882) of 128MB shader cache per game.
