### ISSUE TITLE
Black screen and departure from the game

### ISSUE THREAD

**Issue by guglovich** [disks86/VK9#37]
The problem with running the game Lineage 2. Log applying.
[log.txt](https://github.com/disks86/VK9/files/1993294/log.txt)

**Comment by disks86** [comment]
The the messages in the log seem to indicate that the version of wine you are using doesn't support the debug extensions. Was a VK9.log created?

**Comment by guglovich** [comment]
Yes. Apply
[VK9.log](https://github.com/disks86/VK9/files/1998366/VK9.log)

**Comment by disks86** [comment]
Looks like the issue is the lack of support for the fcr instruction. I'll look into it.

**Comment by guglovich** [comment]
Thank. I'll wait for the test files.

**Comment by redni** [comment]
I think I have a similar error. I compiled the VK9 and tried to run the game. It starts with the whole black screen and disappears after a few seconds. The error messages are similar `Unsupported instruction (...) `and `(...) is not implemented!` I attach the logs. [VK9.log](https://github.com/disks86/VK9/files/2065384/VK9.log)

**Comment by disks86** [comment]
This appears to be a different error but I'll look into it when I can.

**Comment by disks86** [comment]
@redni or @guglovich  can one of you re-test this game with the latest build.

**Comment by guglovich** [comment]
I apologize for the long silence. Unfortunately my game no longer runs through Wine, so I can not say about the working. Changing versions of Wine has not changed anything.

**Comment by guglovich** [comment]
Fixed the game and started with vk9. There are no problems, you can close.
