### ISSUE TITLE
Debug builds require debug libraries

### ISSUE THREAD

**Issue by Monsterovich** [disks86/VK9#44]
It doesn't run.

009d:err:module:import_dll Library MSVCP140D.dll (which is needed by L"Z:\\home\\monsterovich\\Games&Apps\\Star Wars-The Old Republic\\swtor\\RetailClient\\d3d9.dll") not found
009d:err:module:import_dll Library VCRUNTIME140D.dll (which is needed by L"Z:\\home\\monsterovich\\Games&Apps\\Star Wars-The Old Republic\\swtor\\RetailClient\\d3d9.dll") not found
009d:err:module:import_dll Library ucrtbased.dll (which is needed by L"Z:\\home\\monsterovich\\Games&Apps\\Star Wars-The Old Republic\\swtor\\RetailClient\\d3d9.dll") not found

**Comment by Monsterovich** [comment]
Well, I found these dlls on the Internet. It just hangs at 100% CPU and doesn't work anymore. Worked fine in previous version.

**Comment by qwertychouskie** [comment]
@disks86 According to [this](https://social.msdn.microsoft.com/Forums/vstudio/en-US/06b66cae-d010-441d-bc72-64a8c7cd65bc/missing-vcruntime140ddll-and-ucrtbaseddll?forum=visualstudiogeneral), the issue is that they were compiled in debug mode.  The debug DLLs aren't redistributable, see https://stackoverflow.com/questions/39010509/vcruntime140-dll-vs-vcruntime140d-dll.

**Comment by qwertychouskie** [comment]
As far as I understand, the "Debug" builds are useless without the entire Visual Studio installed.  @disks86 could you release some "Release" binaries?  Also the DLLs should have lowercase names (Linux is case-sensitive when it comes to filenames).

**Comment by disks86** [comment]
I believe all you need is the Windows SDK but yes you need the debug libraries. Release builds won't provide nearly as much information in case of a crash but I can include them when I put together the next set of builds.

**Comment by disks86** [comment]
The most recent build contains a release build.
