### ISSUE TITLE
System wide install

### ISSUE THREAD

**Issue by Morganamilo** [disks86/VK9#61]
The wiki states:
>Copy all shaders (*.spv files) and VK9.conf to the location of the executable (exe) of your target application.

Is there any way to install this system wide so these files do not need to be copied per application? I'm assuming the wiki would say so if there was. What I'd really like to know if this is a permanent solution or you eventually intend to remove this requirement?

**Comment by Morganamilo** [comment]
In addition VK9.conf should also be in `/etc/VK9.conf`, perhaps with the the ability to be overridden by `./VK9.conf`. It would also be nice if `VK9.conf` could be renamed to `vk9.conf` to fit in with every other config file.

**Comment by disks86** [comment]
VK9 would run inside of wine so it wouldn't know about /etc/VK9.conf unless your / or /etc/ folder were mapped to a driver letter in wine like Z: or something. I originally planned to embed the shader files in the DLL but decided users may wish to replace them to fiddle with the effects. I'm not opposed to a system wide install but I suspect most people will be using this in a bottle of some sort.

**Comment by Morganamilo** [comment]
By system wide I meant inside of the bottle. I wish to copy the DLL and sharers once, then I can install all of my games inside of that bottle with no additional setup. Bundling the shaders does sound like a way to do it. Maybe instead you could have the shaders also be placed in system 32?

I didn't think about /etc not being accessible though. Is the config optional? The wiki didn't really specify. Having the default settings apply with a missing config would also work.

**Comment by disks86** [comment]
I think I have defaults if the config is missing but when I test I always have the config so you may get undesired behavior. What I was getting at with the bottle is that each game may be in a separate bottle. If that is the case you would still need to copy it for each bottle.

**Comment by Morganamilo** [comment]
>If that is the case you would still need to copy it for each bottle anyway.

True, but I have a winetricks verb to copy it for me. The problem with the shaders are that where I need to copy them to changes on a per game basis. Can't really script that.

**Comment by disks86** [comment]
The shaders are now built into the DLL so I'm going to close this issue.
