### ISSUE TITLE
VK_ERROR_INITIALIZATION_FAILED in all games

### ISSUE THREAD

**Issue by wodim** [disks86/VK9#88]
I'm trying to run it on Windows and all games show a similar log:

    []: RealInstance::RealInstance unable to find renderdoc.dll !
    []: RealSwapChain::InitSwapChain vkCreateSwapchainKHR failed wi[]: RealSwapChain::InitSwapChain vkCreateSwapchainKHR failed with return code of VK_ERROR_INITIALIZATION_FAILED

**Comment by disks86** [comment]
That doesn't happen on my test hardware. Can you tell me the following?

- Version of Windows
- Graphics card model
- Monitor configuration
- Vulkan runtime version

**Comment by wodim** [comment]
* Windows 10 rev 1809
* R9 290
* One monitor, 1920x1200
* Not sure what it could be, the AMD control panel says: Vulkan™ Driver Version: 2.0.64; Vulkan™ API Version: 1.1.86

**Comment by wodim** [comment]
I am sorry, my bad. It's because I was running RivaTuner. After quitting it I no longer get that error.
